### PR TITLE
Bump version to 13.0.4

### PR DESCRIPTION
**Pull request by abadams**
Depends on https://github.com/halide/Halide/pull/6571. The existing version seems to be stale, so I'm not 100% sure this is the right thing.

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
Not sure if we actually use this on the buildbot, but LGTM

**Review by alexreinking — APPROVED** [review]

**Comment by alexreinking** [comment]
I think this is a vestige from before we were sniffing the CMake cache to get version information

**Comment by abadams** [comment]
So is step 3 here defunct? https://github.com/halide/Halide/wiki/Cutting-a-release

**Comment by alexreinking** [comment]
> So is step 3 here defunct? https://github.com/halide/Halide/wiki/Cutting-a-release

Not for major versions, where we still use this table for LLVM

**Pull request merged**
