### PR TITLE
Add release/16.x branch to master config. 

### PR DESCRIPTION
**Pull request by derek-gerstmann**

### CODE REVIEW

**Review by steven-johnson — COMMENTED** [review]
While we're here, we should update LLVM_RELEASE_16 to use 16.0.6, which is the most recent release from https://github.com/llvm/llvm-project/releases

**Comment by derek-gerstmann** [comment]
@steven-johnson Done! I think this may require a restart on the master ...

**Comment by steven-johnson** [comment]
Yes, definitely. I will get to it later today, when the bots are (mostly) quiet, to minimize downtime.

**Comment by derek-gerstmann** [comment]
Perfect!  Thank you!

**Comment by steven-johnson** [comment]
Done

**Pull request merged**
