### PR TITLE
Make changes for cmake based build of hexagon_remote

### PR DESCRIPTION
**Pull request by pranavb-ca**
- Change HL_HEXAGON_SIM_REMOTE and LD_LIBRARY_PATH to reflect new locations of hexagon_sim_remote and libhalide_hexagon_host.so respectively.
- Add HEXAGON_SDK_ROOT to point to the toplevel of the Hexagon SDK
@steven-johnson PTAL

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]

**Comment by steven-johnson** [comment]
Should I go ahead and land this and/or activate it on the buildbot master? (Not sure if we need to also land a Halide PR first to avoid breakage)

**Comment by pranavb-ca** [comment]
> Should I go ahead and land this and/or activate it on the buildbot master? (Not sure if we need to also land a Halide PR first to avoid breakage)

Yes, there is dependency here. We'll need to land Alex's PR https://github.com/halide/Halide/pull/7671 first. 
However, I have a question first. This PR of mine relies on the build property ``HL_HEXAGON_TOOLS`` but I see some builders don't have that property set. This one, for instance, doesn't have the property set -> https://buildbot.halide-lang.org/master/#/builders/89/builds/2 while this one does https://buildbot.halide-lang.org/master/#/builders/65/builds/2

**Comment by steven-johnson** [comment]
OK, I will hold off until I hear more from you.

**Comment by steven-johnson** [comment]
> some builders don't have that property set

Correct: at present we don't do any Hexagon building/testing on anything but x86-64-linux machines; the first one you list is arm-32-linux.

**Comment by pranavb-ca** [comment]
> > some builders don't have that property set
> 
> Correct: at present we don't do any Hexagon building/testing on anything but x86-64-linux machines; the first one you list is arm-32-linux.
Hmm It looks like we do enable the Hexagon backend on platforms other than x86-64.
See https://buildbot.halide-lang.org/master/#/builders/65/builds/15/steps/8/logs/stdio

**Comment by steven-johnson** [comment]
OK, this looks good to me -- if you think it's ready to land, I will merge it and push it out to the buildbot master, please let me know

**Comment by pranavb-ca** [comment]
> OK, this looks good to me -- if you think it's ready to land, I will merge it and push it out to the buildbot master, please let me know

Thank you. I am testing Alex's PR https://github.com/halide/Halide/pull/7671 one last time. Once that is good, I'll confirm here and then this can go in.

**Comment by steven-johnson** [comment]
Monday Morning Ping -- LMK when you are happy with https://github.com/halide/Halide/pull/7671 (and thus, ready for this to land)

**Comment by steven-johnson** [comment]
We can't merge halide/Halide#7671  until the clang-tidy errors are fixed -- we'll be good to go once that happens

**Comment by pranavb-ca** [comment]
Since https://github.com/halide/Halide/pull/7741 has been merged, we can merge this PR as well.

**Comment by pranavb-ca** [comment]
Thank you.

**Pull request merged**
