### PR TITLE
Improve CTest logging

### PR DESCRIPTION
**Pull request by alexreinking**
Add a custom build step for creating CTest command lines. Also piggybacks off of CTest's dashboard reporting features to get detailed output for skipped & failing tests.

All the skipped tests go into one buildbot log, but failing tests each get their own.

Draft mode because I still need to test the failure case and this shouldn't be merged until I do.

Here's an example of what it looks like in the web interface: https://buildbot.alexreinking.com/#/builders/62/builds/25

You can also link to the skip/fail logs directly: https://buildbot.alexreinking.com/#/builders/62/builds/25/steps/12/logs/skipped

### CODE REVIEW

**Comment by alexreinking** [comment]
Here's an example of a CTest test failing and generating a special log in the buildbot run. https://buildbot.alexreinking.com/#/builders/62/builds/32

**Review by steven-johnson — APPROVED** [review]
LGTM. Should we add something in the buildbot README about this?

**Comment by alexreinking** [comment]
> 
> 
> LGTM. Should we add something in the buildbot README about this?

Not sure what to add. It doesn't require any special config.

**Comment by steven-johnson** [comment]
> Not sure what to add. It doesn't require any special config.

I meant more in pointing out that it exists :-)

**Comment by steven-johnson** [comment]
Ready to land? In need of re-review?

**Comment by alexreinking** [comment]
> Ready to land? In need of re-review?

Land #137 first. I merged that into this.

**Pull request merged**
